quickstart / readme added
ConductionNL/NL-Design-System pull request #52
Opened 2022-01-26 20:23 UTC by MWest2020

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2150
| License       | 
| Doc PR        |

2022-01-28 08:00 UTC, lencodes requested changes

2022-01-28 08:00 UTC, lencodes commented on README.md
> +The NL Design Skeleton application is designed for rapid application testing and prototype development on the NL Design System. It provides a basic skeleton application with full NL Design system fun
Misschien goed om hier _NL Design System_ een link te maken naar een plek waar hier iets meer informatie over staat? Denk voor de gemiddelde developer niet direct duidelijk wat hiermee mee wordt bedoeld.

Deze repository provide eigenlijk niet een skeleton application, het provide herbruikbare componenten die conform zijn aan de regels en richtlijnen van _NL Design System_. Het implementeren van deze componenten zorgt ervoor dat je gemakkelijk een applicatie kan maken die daardoor dus ook conform is aan deze richtlijnen. Dit betekent echter niet dat het een skeleton application an sich is (daarvoor hebben we de skeleton app repository).

Het _view locally_ _deploy_ en _demonstration_ gedeelte klopt daardoor ook niet helemaal. Alles wat deze repository doet (of deze npm package) is componenten aanbieden. Daar zit dus niets van deployment o.i.d. bij. De voornaamste voordelen zijn dus denk ik als volgt:

(1) Gemakkelijk en snel applicaties bouwen met pre-built componenten en
(2) Zeker zijn dat je voldoet aan de NL Design System regelgeving (doordat die regelgeving is verwerkt in deze componenten)

2022-01-28 08:00 UTC, lencodes commented on README.md
> +- Development and (online) demonstration of prototypes without the need of a server.
Dit klopt niet, zie bovenstaand comment.

2022-01-28 08:00 UTC, lencodes commented on README.md
> +- An out-of-the-box basic application that doesn't require configuration or setup and can be extended immediately.
Dit klopt niet, zie bovenstaand comment.

2022-01-28 08:00 UTC, lencodes commented on README.md
> +This NL-Design-system repository is a customizable and straightforward component library to help make Progressive Web Applications faster, attractive, and more accessible with React.
Dit klopt beter. Dat het een React component library is, mag denk ik prominenter zijn.

2022-01-28 08:00 UTC, lencodes commented on README.md
> +yarn @conductionnl/nl-design-system
Mogen `$` tekens voor de commands.

De yarn command mist nog het keyword `add`, dus: `$ yarn add @cond....`

2022-01-28 08:00 UTC, lencodes commented on README.md
> +```
Dit klopt gedeeltelijk hoe je het nu hebt opgeschreven. Conceptueel werkt een component package (en dus ook deze) als volgt:

**Package (provider) side:**
(1) In de package worden componenten gebouwd, waar variabelen (of in React terms `props`) aan meegegeven kunnen worden;
(2) Deze componenten worden exported;

**Client (consumer) side:**
(3) De package kan geïnstalleerd worden in een code base (m.b.v. e.g. `npm i ...` zoals eerder omschreven);
(4) De individuele componenten kunnen ingeladen worden in bestanden, layouts, componenten, whatever;
(5) De ingeladen componenten kunnen nu d.m.v. `props` customised worden.

Bovenstaand betekent dat de consumer side nooit de code van de componenten hoeft te zien (dat is juist heel het punt, daar hoeven ze niet meer over na te denken), maar deze code toon je nu wel in de _Usage_.

Dus de usage komt eigenlijk neer op het volgende (ik heb even het component `InfoTooltip` genomen, omdat we deze recentelijk netjes in Typescript hebben geschreven):

```TS
// All components come with prop autocompletion shown directly in your IDE

Import { InfoTooltip } from "@conductionnl/nl-design-system"

<InfoTooltip  content={<>Pass any JSX.Element here</>} placement={"bottom"} /> 
```

2022-02-02 11:48 UTC, MWest2020 commented
Feeback verwerkt

2022-02-04 08:46 UTC, merged